SELECT DISTINCT(`CITY`) FROM STATION WHERE `CITY` REGEXP('^[^aeiou]|[^aeiou]$')

-- or

SELECT DISTINCT(`CITY`) FROM STATION WHERE `CITY` REGEXP('^[^aeiou]') OR `CITY` REGEXP('[^aeiou]$')

-- or

SELECT DISTINCT(`CITY`) FROM STATION WHERE REGEXP_LIKE(`CITY`, '^[^aeiou]|[^aeiou]$')

-- or

SELECT DISTINCT(`CITY`) FROM STATION WHERE REGEXP_LIKE(`CITY`, '^[^aeiou]') OR REGEXP_LIKE(`CITY`, '[^aeiou]$')